# 异常处理

* 每个方法在被编译为字节码时，编译器会为其附加上异常表

如下，字节码中的`trycatchblock`

```java
private static void foo(String[] args) {
        try {
            bar(args);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
    }
```

```bytecode
 // access flags 0xA
  private static foo([Ljava/lang/String;)V
    TRYCATCHBLOCK L0 L1 L2 java/lang/NumberFormatException 
   L0
    LINENUMBER 11 L0
    ALOAD 0
    INVOKESTATIC ch10/ParseIntTest.bar ([Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    GOTO L3
   L2
    LINENUMBER 12 L2
   FRAME SAME1 java/lang/NumberFormatException
    ASTORE 1
   L4
    LINENUMBER 13 L4
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/lang/NumberFormatException.getMessage ()Ljava/lang/String;
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
   L3
    LINENUMBER 15 L3
   FRAME SAME
    RETURN
   L5
    LOCALVARIABLE e Ljava/lang/NumberFormatException; L4 L3 1
    LOCALVARIABLE args [Ljava/lang/String; L0 L5 0
    MAXSTACK = 2
    MAXLOCALS = 2
```

`throw new IndexOutOfBoundsException()`

* 该语句首先会调用 `IndexOutOfBoundsException` 的构造函数及其父类的构造函数：-->...-->Throwable()
* `Throwable` 的构造函数中，会调用 native 方法 `fillInStackTrace(0)`，该方法可以获取当前虚拟机内的调用栈信息，并保存到 `Throwable` 对象的字段中
* 构造函数执行完毕，会执行 `throw`，而 `throw` 在实际执行过程中，会从当前调用栈（方法栈）的异常表中开始查找符合条件的 `exception_handler`，这些 `handler` 即 `catch`、`finally` 等语句块被编译后的统一组织形式。
* 如果没有找到，就往上一层调用栈中查找，如果没有找到符合条件的调用栈，则打印 `IndexOutOfBoundsException` 在构造时保存的调用栈信息。
* 如果找到，则将下一条指令的“地址”设置为 `handler` 的“地址”